Refactored namespaces
Pluralized namespaces (avoids Compiler Error CS0118 Namespace Used As A Type which basically is a conflict error between the name of a class and a namespace)